go:
    # Whenever the Go version is updated here,
    # .circle/config.yml should also be updated.
    version: 1.15
repository:
    path: github.com/prometheus/snmp_exporter
build:
    flags: -trimpath -a -tags netgo -mod vendor
    ldflags: -X 'main.Version=1.1.0'
tarball:
    files:
        - snmp.yml
        - LICENSE
        - NOTICE
